[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
aws-sdk-s3 = "0.0.26-alpha"
aws-config = "0.0.26-alpha"
bytes = "1.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"




