apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: default
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS test;

    USE test;

    CREATE TABLE IF NOT EXISTS my_table (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        data LONGTEXT NOT NULL
    );
